# Generated by Django 2.1.15 on 2020-01-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingrdients',
            new_name='ingredients',
        ),
    ]
