# Generated by Django 2.1.15 on 2020-01-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200130_0808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
